version: "0.1.0"

name: kaluger-projects
services:
  authorization-client:
    env_file:
      - ./environment/authorization-client.env
    volumes:
      - type: bind
        source: ../../authorization-client
        target: /app
      - type: volume
        source: authorization-client-node-modules
        target: /app/node_modules       
    build:
      ../../authorization-client
    ports:
      - 3021:3021
    depends_on:
      - authorization-server
    networks:
      - kaluger-projects
      
  authorization-server:
    env_file:
      - ./environment/authorization-server.env
    volumes:
      - type: bind
        source: ../../authorization-server
        target: /app
      - type: volume
        source: authorization-server-node-modules
        target: /app/node_modules       
    build:
      ../../authorization-server
    ports:
      - 3022:3022
    depends_on:
      - authorization-postgres
    networks:
      - kaluger-projects

  authorization-postgres:
    env_file:
      - ./environment/db.env
    image: postgres:14.8-alpine
    environment:
      POSTGRES_DB: authorization
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - authorization-postgres:/var/lib/postgresql/data/pgdata
    ports:
      - 3023:5432
    networks:
      - kaluger-projects

  sound-english-client:
    env_file:
      - ./environment/sound-english-client.env
    volumes:
      - type: bind
        source: ../../sound-english-client
        target: /app
      - type: volume
        source: sound-english-client-node-modules
        target: /app/node_modules       
    build:
      ../../sound-english-client
    ports:
      - 3024:3024
    depends_on:
      - sound-english-server
    networks:
      - kaluger-projects

  sound-english-server:
    env_file:
      - ./environment/sound-english-server.env
    volumes:
      - type: bind
        source: ../../sound-english-server
        target: /app
      - type: volume
        source: sound-english-server-node-modules
        target: /app/node_modules       
      - type: volume
        source: sound-english-server-audios
        target: /app/audios       
    build:
      ../../sound-english-server
    ports:
      - 3025:3025
    depends_on:
      - sound-english-postgres
    networks:
      - kaluger-projects

  sound-english-postgres:
    env_file:
      - ./environment/db.env
    image: postgres:14.8-alpine
    environment:
      POSTGRES_DB: sound-english
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - sound-english-postgres:/var/lib/postgresql/data/pgdata
    ports:
      - 3026:5432
    networks:
      - kaluger-projects

  text-to-speech:
    image: aculeasis/rhvoice-rest
    ports:
      - 3027:8080
    networks:
      - kaluger-projects
    
  translate:
    image: libretranslate/libretranslate
    ports:
      - 3028:5000
    networks:
      - kaluger-projects

  ffmpeg-server:
    env_file:
      - ./environment/ffmpeg-server.env
    volumes:
      - type: bind
        source: ../../ffmpeg-server
        target: /app
      - type: volume
        source: ffmpeg-server-node-modules
        target: /app/node_modules       
      - type: volume
        source: sound-english-server-audios
        target: /app/audios       
    build:
      ../../ffmpeg-server
    ports:
      - 3029:3000
    networks:
      - kaluger-projects

volumes:
  authorization-postgres:
  sound-english-postgres:
  authorization-client-node-modules:
  authorization-server-node-modules:
  sound-english-server-audios:
  sound-english-server-node-modules:
  sound-english-client-node-modules:
  ffmpeg-server-node-modules:

networks:
  kaluger-projects:
    driver: bridge